// swift-tools-version:5.9
// This Package.swift is for development/compilation verification only.
// The actual app is built via the Xcode project (generated by XcodeGen).
// Note: Messages framework imports will not resolve in SPM context,
// but all game logic and models can be verified.

import PackageDescription

let package = Package(
    name: "ScrabbleMessage",
    platforms: [.iOS(.v16), .macOS(.v13)],
    targets: [
        .target(
            name: "ScrabbleGameLogic",
            path: "MessagesExtension",
            exclude: ["Info.plist", "Assets.xcassets", "Resources", "Serialization/MessageComposer.swift"],
            sources: ["Models", "Logic", "Serialization"]
        ),
    ]
)
